### ISSUE TITLE
ABlock 클래스의 최적화 방안(일지도..?) 및 Argument 클래스의 필요 이유에 관한 질문

### ISSUE THREAD

**Issue by RanolP** [DevCrafters/BlockCoding#1]
## ABlock
1. validArgument(Argument...)에서 람다와 스트림 API를 사용하는데 성능 이슈는 없나요? 만약 있다면 for를 사용하는 것은 어떤가요?
  1-1. 만약 람다를 사용할 것이라면 a -> a.getName()을 Argument::getName로 바꿀 생각 없나요?
1. 인수가 요구하는 개수보다 적을 경우 내부에서 리스트 카피 후 removeAll을 하는데 더 나은 방법은 없나요?
1. 받을 수 없는 인수를 체크할 때 removeAll을 사용하는데 더 나은 방법은 없나요?
1. Argument라는 클래스가 존재하는데 Argument만 혹은 String, String만 사용하는게 좋지 않을까요?
1. 현재의 ABlock의 형태로는 if와 같은 함수를 만들 경우 블럭 목록을 저장하나요? 아니면 jump와 유사한 명령으로 치환되나요?

## Argument
1. 과연 이것이 필요할까요? 어차피 사용자는 내부 동작을 보지 못하니 객체 생성을 하지 않고 String, String을 보내는 것이 성능쪽에서 나을 수도 있지 않을까요?

**Comment by RanolP** [comment]
1, 2, 3은 전부 validArgument(Argument...)에 관한 이야기 입니다.

**Comment by PeraSite** [comment]
- vaildArgument의 람다, 스트림 부분을 for문으로 교체했고 
성능이 114% (벤치마킹 100만번 실행 시 전 150ms -> 후 70~80ms) 향상되었습니다.

- removeAll 부분의 코드를 다른 코드로 대체해보았지만 더 빠른 코드는 찾을 수 없었습니다.
다만, 무조건 removeAll이 아니라 매개변수 목록의 크기와 허용된 매개변수 목록의 크기가
다를 경우에만 removeAll을 하게 수정했습니다. 성능은 약 16% 정도 향상되었습니다.

- Argument 클래스를 대체해 String 2개를 받을 수 있는 방법을 찾지 못했습니다.
MapBuilder같은 유틸 클래스를 이용해 맵을 만들 수도 있겠으나, 가독성을 고려해보았을 때 현재 방법이
가장 낫다고 판단했습니다.
